spring.application.name=order-service
server.port=${ORDER_SERVICE_PORT:8085}

spring.datasource.url=${ORDER_DB_URL:jdbc:mysql://localhost:3306/order_db}
spring.datasource.username=${ORDER_DB_USERNAME:root}
spring.datasource.password=${ORDER_DB_PASSWORD:change_me}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:host.docker.internal:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

app.jwt.secret=${JWT_SECRET:change-me-change-me-change-me-1234}
