spring.application.name=product-service

server.port=${PRODUCT_SERVICE_PORT:8083}

spring.datasource.url=${PRODUCT_DB_URL:jdbc:mysql://localhost:3306/product_db}
spring.datasource.username=${PRODUCT_DB_USERNAME:root}
spring.datasource.password=${PRODUCT_DB_PASSWORD:change_me}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=${JWT_SECRET:change-me-change-me-change-me-1234}
